services:
  stock-publisher:
    restart: always
    image: janik1998/microservices_mr_ju-stock-publisher
    container_name: stock-publisher
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://stockmarket:supersecret123@rabbitmq:5672/
    ports:
      - "8080:8080" #Mapping

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Port für die Verbindung von Producer und Consumer
      - "15672:15672" # Port für das Management-Interface
    environment:
      RABBITMQ_DEFAULT_USER: stockmarket
      RABBITMQ_DEFAULT_PASS: supersecret123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
      
  stockmarket1:
    image: mongo:7.0
    ports:
      - 27017:27017
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]    
    extra_hosts: 
        - "host.docker.internal:host-gateway" 
    healthcheck: 
      test: echo "try { rs.status() } catch (err) {rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017',priority:1},{_id:1,host:'host.docker.internal:27018',priority:0.5},{_id:2,host:'host.docker.internal:27019',priority:0.5}]}) }" | mongosh --port 27017 --quiet 
      interval: 5s 
      timeout: 30s 
      start_period: 0s 
      start_interval: 1s 
      retries: 30
    volumes: 
      - "stockmarket1_data:/data/db" 
      - "stockmarket1_config:/data/configdb" 
    
  stockmarket2: 
    image: mongo:7.0 
    ports: 
      - 27018:27018
    extra_hosts: 
      - "host.docker.internal:host-gateway" 
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018"] 
    volumes: 
      - "stockmarket2_data:/data/db" 
      - "stockmarket2_config:/data/configdb" 

  stockmarket3: 
    image: mongo:7.0 
    ports: 
      - 27019:27019   
    extra_hosts: 
        - "host.docker.internal:host-gateway" 
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27019"]
    volumes: 
      - "stockmarket3_data:/data/db" 
      - "stockmarket3_config:/data/configdb"  

  stock-liveview-master1:
    restart: always
    image: janik1998/stock-liveview-master:1.0
    container_name: stock-liveview-master1
    depends_on:
      - stockmarket1
      - stockmarket2
      - stockmarket3
    environment:
      - MONGODB_URL=mongodb://stockmarket1:27017,stockmarket2:27018,stockmarket3:27019/mydatabase?replicaSet=rs0

  stock-liveview-master2:
    restart: always
    image: janik1998/stock-liveview-master:1.0
    container_name: stock-liveview-master2
    depends_on:
      - stockmarket1
      - stockmarket2
      - stockmarket3
    environment:
      - MONGODB_URL=mongodb://stockmarket1:27017,stockmarket2:27018,stockmarket3:27019/mydatabase?replicaSet=rs0
    ports:
      - 3200:3000

  nginx-loadbalancer:
    image: nginx:latest
    container_name: nginx-loadbalancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - stock-liveview-master1
      - stock-liveview-master2
      
volumes:
  rabbitmq_data:
  stockmarket1_data: 
  stockmarket2_data: 
  stockmarket3_data: 
  stockmarket1_config: 
  stockmarket2_config: 
  stockmarket3_config: 
