services:
  stock-publisher:
    build:
      context: ./stock-publisher
    container_name: stock-publisher
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    ports:
      - "8080:8080" #Mapping

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Port für die Verbindung von Producer und Consumer
      - "15672:15672" # Port für das Management-Interface
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq   

volumes:
  rabbitmq_data: