services:
  stock-publisher:
    restart: always
    image: janik1998/microservices_mr_ju-stock-publisher
    container_name: stock-publisher
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://stockmarket:supersecret123@rabbitmq:5672/
    ports:
      - "8080:8080" #Mapping

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Port für die Verbindung von Producer und Consumer
      - "15672:15672" # Port für das Management-Interface
    environment:
      RABBITMQ_DEFAULT_USER: stockmarket
      RABBITMQ_DEFAULT_PASS: supersecret123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
      
  stockmarket1:
    image: mongo:7.0
    ports:
      - 27017:27017
  stockmarket2: 
    image: mongo:7.0 
    ports: 
      - 27018:27018 
  stockmarket3: 
    image: mongo:7.0 
    ports: 
      - 27019:27019   

volumes:
  rabbitmq_data:

